library(ggforce)

ONT = read.xlsx("ONT.xlsx", sheet = 1)
ILMN = read.xlsx("ILMN.xlsx", sheet = 1) %>% mutate(Lab = gsub("_.*", "", Lab))
MGI = read.xlsx("MGI.xlsx", sheet = 1) %>% mutate(Lab = gsub("_.*", "", Lab))

ONT_prefix = "SD-003-8"
ONT_lab = "clinical"

example_ONT = ONT %>% dplyr::filter(Prefix == ONT_prefix & Lab == ONT_lab) %>% select(ends_with("P")) %>% pivot_longer(everything(), names_to = "Method", values_to = "value") %>% separate(Method, c("Genome", "Algorithm", "Measure")) %>% unite("Method", Genome, Algorithm) %>% mutate(Method = factor(Method, levels = unique(Method))) %>% group_by(Method) %>% summarize(Host = sum(value), Non_host = ONT %>% dplyr::filter(Prefix == ONT_prefix & Lab == ONT_lab) %>% select(Clean_Reads) %>% pull() - sum(value), .groups = "drop") %>% mutate(Multi_labels = NA, Host_sensu_lato = NA) %>% rows_insert(data.frame(Method = "o"), by = "Method") %>% rows_insert(ONT %>% dplyr::filter(Prefix == ONT_prefix & Lab == ONT_lab) %>% transmute(Method = "consensus", Host = Host_consensus, Non_host = Non_host_consensus, Multi_labels = Multi_labels, Host_sensu_lato = Host_when_loosen_restrictions), by = "Method") %>% rows_insert(data.frame(Method = "e"), by = "Method") %>% rows_insert(ONT %>% dplyr::filter(Prefix == ONT_prefix & Lab == ONT_lab) %>% transmute(Method = "ground_truth", Host = Host_reads_ground_truth, Non_host = ONT %>% dplyr::filter(Prefix == ONT_prefix & Lab == ONT_lab) %>% select(Clean_Reads) %>% pull() - Host_reads_ground_truth), by = "Method") %>% mutate(Method = factor(Method, levels = unique(Method)))

p_ONT <- ggplot(example_ONT %>% pivot_longer(-c(Method, Host_sensu_lato), "Label") %>% mutate(Label = factor(Label, levels = c("Non_host", "Multi_labels", "Host"))), aes(x = Method, y = value, fill = Label)) + geom_bar(stat = "identity", position = "stack")  + theme_classic() + scale_fill_manual(values = c("#A6CEE3", "grey90", "#FB9A99")) + labs(y = "Reads Count", x = "") + theme(axis.text.x = element_text(angle = 30, hjust = 1))
ggsave("Example_ONT.png", p_ONT + geom_col() + facet_zoom(ylim = c(77000, 81000), show.area = T), height = 9, width = 15)

ILMN_prefix = "R3-1-U62_S11_R1_001"
ILMN_lab = "clinical"

example_ILMN = ILMN %>% dplyr::filter(Prefix == ILMN_prefix & Lab == ILMN_lab) %>% select(ends_with("P")) %>% pivot_longer(everything(), names_to = "Method", values_to = "value") %>% mutate(Method = gsub("tie2_v", "tie2@v", gsub("bwa_m", "bwa@m", Method))) %>% separate(Method, c("Genome", "Algorithm", "Measure"), sep = "_") %>% mutate(Algorithm = gsub("tie2@v", "tie2_v", gsub("bwa@m", "bwa_m", Algorithm))) %>% unite("Method", Genome, Algorithm) %>% mutate(Method = factor(Method, levels = unique(Method))) %>% group_by(Method) %>% summarize(Host = sum(value), Non_host = ILMN %>% dplyr::filter(Prefix == ILMN_prefix & Lab == ILMN_lab) %>% select(Clean_Reads) %>% pull() - sum(value), .groups = "drop") %>% mutate(Multi_labels = NA, Host_sensu_lato = NA) %>% rows_insert(data.frame(Method = "o"), by = "Method") %>% rows_insert(ILMN %>% dplyr::filter(Prefix == ILMN_prefix & Lab == ILMN_lab) %>% transmute(Method = "consensus", Host = Host_consensus, Non_host = Non_host_consensus, Multi_labels = Multi_labels, Host_sensu_lato = Host_when_loosen_restrictions), by = "Method") %>% rows_insert(data.frame(Method = "e"), by = "Method") %>% rows_insert(ILMN %>% dplyr::filter(Prefix == ILMN_prefix & Lab == ILMN_lab) %>% transmute(Method = "ground_truth", Host = Host_reads_ground_truth, Non_host = ILMN %>% dplyr::filter(Prefix == ILMN_prefix & Lab == ILMN_lab) %>% select(Clean_Reads) %>% pull() - Host_reads_ground_truth), by = "Method") %>% mutate(Method = factor(Method, levels = unique(Method)))

p_ILMN <- ggplot(example_ILMN %>% pivot_longer(-c(Method, Host_sensu_lato), "Label") %>% mutate(Label = factor(Label, levels = c("Non_host", "Multi_labels", "Host"))), aes(x = Method, y = value, fill = Label)) + geom_bar(stat = "identity", position = "stack")  + theme_classic() + scale_fill_manual(values = c("#A6CEE3", "grey90", "#FB9A99")) + labs(y = "Reads Count", x = "") + theme(axis.text.x = element_text(angle = 30, hjust = 1))
ggsave("Example_ILMN.png", p_ILMN + geom_col() + facet_zoom(ylim = c(7000000, 11000000), show.area = T), height = 9, width = 15)