library(rstatix)

#ILMN %>% select(Lab, Sample, ends_with("MCC")) %>% unite("Sample", c(Sample, Lab)) %>% mutate(Sample = factor(Sample, levels = unique(Sample))) %>% mutate(across(ends_with("MCC"), function(x) x - T2T_kraken2_MCC)) %>% pivot_longer(ends_with("MCC"), "Method", values_to = "MCC") %>% dplyr::filter(Method != "T2T_kraken2_MCC") %>% group_by(Method) %>% shapiro_test(MCC)

#ggsave("ILMN_MCC_d_qqplot.png", ggplot(ILMN %>% select(Lab, Sample, ends_with("MCC")) %>% unite("Sample", c(Sample, Lab)) %>% mutate(Sample = factor(Sample, levels = unique(Sample))) %>% mutate(across(ends_with("MCC"), function(x) x - T2T_kraken2_MCC)) %>% pivot_longer(ends_with("MCC"), "Method") %>% mutate(Method = gsub("2_v", "2v", Method)) %>% mutate(Method = gsub("a_m", "am", Method)) %>% separate(Method, c("Genome", "Algorithm", "Measure")) %>% mutate(Genome = factor(Genome, levels = c("hg38", "T2T", "YH")), Algorithm = factor(Algorithm, levels = c("bowtie2vf", "bowtie2vs", "bwamem", "minimap2", "winnowmap", "STAT", "kraken2")))) + geom_qq(aes(sample = value)) + stat_qq_line(aes(sample = value), color = "red") + facet_wrap(.~Genome+Algorithm), height = 6, width = 9)


p_qq_ILMN <- ggplot(ILMN %>% select(Lab, Sample, ends_with("MCC")) %>% unite("Sample", c(Sample, Lab)) %>% mutate(Sample = factor(Sample, levels = unique(Sample))) %>% mutate(across(ends_with("MCC"), function(x) x - T2T__kraken2__MCC)) %>% pivot_longer(ends_with("MCC"), "Method") %>% separate(Method, c("Genome", "Algorithm", "Measure"), sep = "__")) + geom_qq(aes(sample = value)) + stat_qq_line(aes(sample = value), color = "red") + labs(y = "Pairwise difference quantiles", x = "Normal distribution quantiles") + facet_wrap(.~Genome+Algorithm)
p_qq_MGI <- ggplot(MGI %>% select(Lab, Sample, ends_with("MCC")) %>% unite("Sample", c(Sample, Lab)) %>% mutate(Sample = factor(Sample, levels = unique(Sample))) %>% mutate(across(ends_with("MCC"), function(x) x - T2T__kraken2__MCC)) %>% pivot_longer(ends_with("MCC"), "Method") %>% separate(Method, c("Genome", "Algorithm", "Measure"), sep = "__")) + geom_qq(aes(sample = value)) + stat_qq_line(aes(sample = value), color = "red") + labs(y = "Pairwise difference quantiles", x = "Normal distribution quantiles") + facet_wrap(.~Genome+Algorithm)
p_qq_ONT <- ggplot(ONT %>% select(Lab, Sample, ends_with("MCC")) %>% unite("Sample", c(Sample, Lab)) %>% mutate(Sample = factor(Sample, levels = unique(Sample))) %>% mutate(across(ends_with("MCC"), function(x) x - T2T__kraken2__MCC)) %>% pivot_longer(ends_with("MCC"), "Method") %>% separate(Method, c("Genome", "Algorithm", "Measure"), sep = "__")) + geom_qq(aes(sample = value)) + stat_qq_line(aes(sample = value), color = "red") + labs(y = "Pairwise difference quantiles", x = "Normal distribution quantiles") + facet_wrap(.~Genome+Algorithm)
p_qq_ILMN + p_qq_MGI + p_qq_ONT + plot_annotation(tag_levels = "A") + plot_layout(ncol = 1)
ggsave("Figure S6 QQ plots of MCC.pdf", h = 24, w = 9)